[package]
name = "du-dust"
description = "A more intuitive version of du"
version = "0.5.1"
authors = ["bootandy <bootandy@gmail.com>", "nebkor <code@ardent.nebcorp.com>"]
edition = "2018"

documentation = "https://github.com/bootandy/dust"
homepage = "https://github.com/bootandy/dust"
repository = "https://github.com/bootandy/dust"

keywords = ["du", "command-line", "disk", "disk-usage"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[badges]
travis-ci = {repository = "https://travis-ci.org/bootandy/dust"}

[[bin]]
name = "dust"
path = "src/main.rs"

[dependencies]
ansi_term = "=0.12"
clap = "=2.33"
jwalk = "0.4.0"
lscolors = "0.6.0"
num_cpus = "1.12"
terminal_size = "0.1.10"
unicode-width = "0.1.7"

[target.'cfg(windows)'.dependencies]
winapi-util = "0.1"

[dev-dependencies]
assert_cli = "=0.6"
tempfile = "=3"


[[test]]
name = "integration"
path = "tests/tests.rs"

[patch.crates-io]
unicode-width = { git = "https://github.com/waltarix/unicode-width", tag = "0.1.7-custom-r2" }
